spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
  flyway:
    enabled: true
    locations: classpath:db/migrations
    baseline-on-migrate: true
    out-of-order: true


api:
  bookstore-endpoint: https://api.bookstore.com/v1