
dependencies {
    implementation project(':service')
    implementation project(':persistence')
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    testImplementation "org.testcontainers:kafka"
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
    testImplementation 'org.flywaydb:flyway-core'
    testImplementation 'com.approvaltests:approvaltests:24.22.0'
    testImplementation 'com.google.code.gson:gson:2.13.1'
    testImplementation 'org.awaitility:awaitility:4.3.0'
}

dependencyManagement {
    imports {
        mavenBom "org.testcontainers:testcontainers-bom:1.19.0"
    }
}

dependencyManagement {
    imports {
        mavenBom "org.testcontainers:testcontainers-bom:1.19.0"
    }
}
